### ISSUE TITLE
Unutilized variable - o365cli_app_catalog_scope

### ISSUE THREAD

**Issue by phil-maynard** [svarukala/O365CLI-Cert-SPFX-CICD-Pipeline#2]
### Description
The variable **o365cli_app_catalog_scope** is declared in the variables section but then not referenced in the Upload or Deploy sections

### Details
For development purposes, it's useful to be able to upload and deploy to a site collection app catalog. Having the declared variable used in the script would be super useful. It may also be worth adding a comment with the possible options e.g. tennant/sitecollection

### Note
Thanks for your work on this. It's been incredibly helpful using your example to deploy SPFx packages using app certificate authentication

**Comment by svarukala** [comment]
Hello @phil-maynard,
You can use the scope with O365 CLI as follows:
        ##########################################
        ## upload *.sppkg to the target app catalog
        ##########################################
        - script: o365 spo app add --filePath "$(Pipeline.Workspace)/spfx-package/$(GetSharePointPackage.SpPkgFileName)" --appCatalogUrl ${{ parameters.o365_app_catalog_site_url }} --scope ${{ parameters.o365cli_app_catalog_scope }} --overwrite ${{ parameters.o365cli_spoAppAdd_extra_arguments }}
          displayName: Upload SharePoint package to Site Collection App Catalog

See this for the O365 CLI 'spo app add' command help:
https://pnp.github.io/cli-microsoft365/cmd/spo/app/app-add/

More details about site collection scoped app catalog:
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog

I am glad this was helpful to your project. 

You can find the Yaml job templates for spfx deployment here:
https://dev.azure.com/svarukal/_git/SPFX-Pipelines-Templates?path=%2Fjobs
